<?php

$plugin = array(
  'title' => t('Site template'),
  'theme' => 'idpo_site_template',
  'icon' => 'idpo-site-template.png',
  'category' => 'Idrottsportalen',
  'regions' => array(
    'secondary_menu' => t('Secondary menu'),
    'branding_logo' => t('Branding logo'),
    'branding_left' => t('Branding left'),
    'branding_right' => t('Branding right'),
    'nav' => t('Navigation'),
    'main' => t('Main'),
    'sitemap' => t('Sitemap'),
    'footer' => t('Footer'),
  ),
);